databases:
  - name: postgres
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: Repthon
    env: python
    buildCommand: ./build.sh
    startCommand: bash repub
    region: frankfurt
    envVars:
      - key: ALIVE_NAME
        sync: false
      - key: APP_ID 
        value: 13740761
      - key: API_HASH 
        value: 4ce319a92c01fab2b02551af8d7f73a4
      - key: ENV 
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_USERNAME
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: TZ
        value: Asia/Baghdad
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString   
    autoDeploy: false
